workflows:
  code-check:
    name: Code Check
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      java: 17
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Run detekt
        script: |
          ./gradlew detekt
      - name: Run tests
        script: |
          ./gradlew :main:testDebugUnitTest
    artifacts:
      - build/**/reports/detekt/detekt.html
      - build/**/reports/tests/testDebugUnitTest/index.html